export const SET_TASKS = "SET_TASKS";
export const SET_TASK = "SET_TASK";
export const TOGGLE_PLUS = "TOGGLE_PLUS";
export const EDIT_PROFILE = "EDIT_PROFILE";
export const SET_PROFILE = "SET_PROFILE";

export const SET_CONTACTS = "SET_CONTACTS";
export const ADD_TO_CONTACTS = "ADD_TO_CONTACTS";
export const DELETE_CONTACTS = "DELETE_CONTACTS";
export const ADD_TO_SELECTED_CONTACTS = "ADD_TO_SELECTED_CONTACTS";
export const SET_SELECTED_CONTACTS = "SET_SELECTED_CONTACTS";
export const SET_ANY_CONTACT_SELECTED_BOOLEAN = "SET_ANY_CONTACT_SELECTED_BOOLEAN";
export const CLEAR_SELECTED_CONTACTS = "CLEAR_SELECTED_CONTACTS";
